// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL3Q8_emP_S_6wK7f71cIra8r0IryJjyA',
    appId: '1:307971430786:web:a4470dda9af3a4e0bed79b',
    messagingSenderId: '307971430786',
    projectId: 'park-flutter-app-test',
    authDomain: 'park-flutter-app-test.firebaseapp.com',
    storageBucket: 'park-flutter-app-test.appspot.com',
    measurementId: 'G-TBZZ73N7FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCThBDbOiAEWmEZeN0jJb9sgRGIWOUoBro',
    appId: '1:307971430786:android:f4377971898545babed79b',
    messagingSenderId: '307971430786',
    projectId: 'park-flutter-app-test',
    storageBucket: 'park-flutter-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1wRXP9E9_WLpk7NkN0zEAyPAYuJTaHQU',
    appId: '1:307971430786:ios:1bfed91de886135cbed79b',
    messagingSenderId: '307971430786',
    projectId: 'park-flutter-app-test',
    storageBucket: 'park-flutter-app-test.appspot.com',
    iosClientId: '307971430786-c08hh00gsjvgief2fncl2ahjmm6an0sf.apps.googleusercontent.com',
    iosBundleId: 'co.weirdsector.flutterAppTest',
  );
}
